# Dockerfile_cliente_automatico_js

# Use uma imagem oficial do Node.js
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Instala as dependências (zeromq e msgpack)
# Não precisamos de um package.json para este exemplo simples
RUN npm install zeromq @msgpack/msgpack

# Copie o código-fonte do cliente
COPY cliente_automatico.js .

# Comando para rodar o script
# (O 'node' não precisa do -u igual ao python)
CMD ["node", "cliente_automatico.js"]